### ISSUE TITLE
[Meta] Explore coverage and find a function to improve

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/thinkr#16]
Code coverage is there: https://codecov.io/github/ThinkR-open/thinkr?branch=master

- Find a function that is not well covered.
- Open an issue to say that you are working on it
- Add these checkbox
```
- [ ] Document the function
- [ ] Add a reproducible example
- [ ] Add unit tests
- [ ] Add a dedicated vignette
```
You can use {fusen} and `fusen::add_dev_history(name = "additional")` to do so. While doing this, you will need to cut the code of the chosen from the associated R file to put it in the `function` chunk of the dev_history. {fusen} documentation is there: https://thinkr-open.github.io/fusen/
